In [1]:
from warnings import filterwarnings
filterwarnings('ignore')

In [2]:
import pandas as pd 
df = pd.read_csv('C:Downloads/Cars93.csv')

In [3]:
df.head()

id Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0   1        Acura  Integra    Small       12.9   15.9       18.8        25   
1   2        Acura   Legend  Midsize       29.2   33.9       38.7        18   
2   3         Audi       90  Compact       25.9   29.1       32.3        20   
3   4         Audi      100  Midsize       30.8   37.7       44.6        19   
4   5          BMW     535i  Midsize       23.7   30.0       36.2        22   

   MPG.highway             AirBags  ... Passengers Length  Wheelbase  Width  \
0           31                 NaN  ...          5    177        102     68   
1           25  Driver & Passenger  ...          5    195        115     71   
2           26         Driver only  ...          5    180        102     67   
3           26                 NaN  ...          6    193        106     70   
4           30         Driver only  ...          4    186        109     69   

   Turn.circle  Rear.seat.room Luggage.room  Weight   Origin           Make  
0           37            26.5         11.0    2705  non-USA  Acura Integra  
1           38            30.0         15.0    3560  non-USA   Acura Legend  
2           37            28.0         14.0    3375  non-USA        Audi 90  
3           37            31.0         17.0    3405  non-USA       Audi 100  
4           39            27.0         13.0    3640  non-USA       BMW 535i  

[5 rows x 28 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 28 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   id                  93 non-null     int64  
 1   Manufacturer        93 non-null     object 
 2   Model               93 non-null     object 
 3   Type                93 non-null     object 
 4   Min.Price           93 non-null     float64
 5   Price               93 non-null     float64
 6   Max.Price           93 non-null     float64
 7   MPG.city            93 non-null     int64  
 8   MPG.highway         93 non-null     int64  
 9   AirBags             56 non-null     object 
 10  DriveTrain          93 non-null     object 
 11  Cylinders           93 non-null     object 
 12  EngineSize          93 non-null     float64
 13  Horsepower          93 non-null     int64  
 14  RPM                 93 non-null     int64  
 15  Rev.per.mile        93 non-null     int64  
 16  Man.trans.

In [5]:
s = df.isna().sum()

In [6]:
s = s[s>0]
s

AirBags           37
Rear.seat.room     2
Luggage.room      11
dtype: int64

# SEPRATE X AND Y 

In [7]:
X = df.drop(columns=['id','Weight'])

In [8]:
X.head()

Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0        Acura  Integra    Small       12.9   15.9       18.8        25   
1        Acura   Legend  Midsize       29.2   33.9       38.7        18   
2         Audi       90  Compact       25.9   29.1       32.3        20   
3         Audi      100  Midsize       30.8   37.7       44.6        19   
4          BMW     535i  Midsize       23.7   30.0       36.2        22   

   MPG.highway             AirBags DriveTrain  ... Fuel.tank.capacity  \
0           31                 NaN      Front  ...               13.2   
1           25  Driver & Passenger      Front  ...               18.0   
2           26         Driver only      Front  ...               16.9   
3           26                 NaN      Front  ...               21.1   
4           30         Driver only       Rear  ...               21.1   

   Passengers  Length  Wheelbase  Width Turn.circle  Rear.seat.room  \
0           5     177        102     68          37            26.5   
1           5     195        115     71          38            30.0   
2           5     180        102     67          37            28.0   
3           6     193        106     70          37            31.0   
4           4     186        109     69          39            27.0   

   Luggage.room   Origin           Make  
0          11.0  non-USA  Acura Integra  
1          15.0  non-USA   Acura Legend  
2          14.0  non-USA        Audi 90  
3          17.0  non-USA       Audi 100  
4          13.0  non-USA       BMW 535i  

[5 rows x 26 columns]

In [9]:
Y = df[['Weight']]
Y.head()

Weight
0    2705
1    3560
2    3375
3    3405
4    3640

# SEPRATE CAT AND CON 

In [10]:
from mylib import catconsep

In [11]:
cat , con = catconsep(X)

In [12]:
cat

['Manufacturer',
 'Model',
 'Type',
 'AirBags',
 'DriveTrain',
 'Cylinders',
 'Man.trans.avail',
 'Origin',
 'Make']

In [13]:
con

['Min.Price',
 'Price',
 'Max.Price',
 'MPG.city',
 'MPG.highway',
 'EngineSize',
 'Horsepower',
 'RPM',
 'Rev.per.mile',
 'Fuel.tank.capacity',
 'Passengers',
 'Length',
 'Wheelbase',
 'Width',
 'Turn.circle',
 'Rear.seat.room',
 'Luggage.room']

# PREPROCESSING PIPELINE 

In [14]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer

In [15]:
#create a numerical pipeline 
num_pipe = Pipeline(steps=[('impute',SimpleImputer(strategy='mean')),
                          ('scaler',StandardScaler())])

#create a cat pipeline 
cat_pipe = Pipeline(steps=[('impute',SimpleImputer(strategy='most_frequent')),
                          ('OHE',OneHotEncoder(handle_unknown='ignore'))])

#comb both cat and con 
pre = ColumnTransformer([('num',num_pipe,con),
                        ('cat',cat_pipe,cat)])

In [16]:
X_pre = pre.fit_transform(X).toarray()

In [17]:
X_pre

array([[-0.48578741, -0.37572014, -0.28246529, ...,  0.        ,
         0.        ,  0.        ],
       [ 1.38801699,  1.49784409,  1.53140881, ...,  0.        ,
         0.        ,  0.        ],
       [ 1.00865782,  0.99822696,  0.94805231, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 0.66378585,  0.39452293,  0.16416702, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.53733279,  0.33207079,  0.14593713, ...,  0.        ,
         1.        ,  0.        ],
       [ 0.88220476,  0.7484184 ,  0.60168439, ...,  0.        ,
         0.        ,  1.        ]])

In [18]:
cols = pre.get_feature_names_out()

In [19]:
cols

array(['num__Min.Price', 'num__Price', 'num__Max.Price', 'num__MPG.city',
       'num__MPG.highway', 'num__EngineSize', 'num__Horsepower',
       'num__RPM', 'num__Rev.per.mile', 'num__Fuel.tank.capacity',
       'num__Passengers', 'num__Length', 'num__Wheelbase', 'num__Width',
       'num__Turn.circle', 'num__Rear.seat.room', 'num__Luggage.room',
       'cat__Manufacturer_Acura', 'cat__Manufacturer_Audi',
       'cat__Manufacturer_BMW', 'cat__Manufacturer_Buick',
       'cat__Manufacturer_Cadillac', 'cat__Manufacturer_Chevrolet',
       'cat__Manufacturer_Chrylser', 'cat__Manufacturer_Chrysler',
       'cat__Manufacturer_Dodge', 'cat__Manufacturer_Eagle',
       'cat__Manufacturer_Ford', 'cat__Manufacturer_Geo',
       'cat__Manufacturer_Honda', 'cat__Manufacturer_Hyundai',
       'cat__Manufacturer_Infiniti', 'cat__Manufacturer_Lexus',
       'cat__Manufacturer_Lincoln', 'cat__Manufacturer_Mazda',
       'cat__Manufacturer_Mercedes-Benz', 'cat__Manufacturer_Mercury',
       'cat__Man

In [20]:
X_pre = pd.DataFrame(X_pre,columns=cols)

In [21]:
X_pre.head()

num__Min.Price  num__Price  num__Max.Price  num__MPG.city  \
0       -0.485787   -0.375720       -0.282465       0.471312   
1        1.388017    1.497844        1.531409      -0.781032   
2        1.008658    0.998227        0.948052      -0.423219   
3        1.571949    1.893374        2.069191      -0.602126   
4        0.755752    1.091905        1.303535      -0.065407   

   num__MPG.highway  num__EngineSize  num__Horsepower  num__RPM  \
0          0.360925        -0.841022        -0.073484  1.717489   
1         -0.770514         0.515869         1.078322  0.369586   
2         -0.581941         0.128186         0.540813  0.369586   
3         -0.581941         0.128186         0.540813  0.369586   
4          0.172352         0.806631         1.231897  0.706562   

   num__Rev.per.mile  num__Fuel.tank.capacity  ...  cat__Make_Toyota Camry  \
0           1.129530                -1.062184  ...                     0.0   
1           0.005661                 0.409445  ...                     0.0   
2          -0.105713                 0.072197  ...                     0.0   
3           0.410659                 1.359872  ...                     0.0   
4           0.430909                 1.359872  ...                     0.0   

   cat__Make_Toyota Celica  cat__Make_Toyota Previa  cat__Make_Toyota Tercel  \
0                      0.0                      0.0                      0.0   
1                      0.0                      0.0                      0.0   
2                      0.0                      0.0                      0.0   
3                      0.0                      0.0                      0.0   
4                      0.0                      0.0                      0.0   

   cat__Make_Volkswagen Corrado  cat__Make_Volkswagen Eurovan  \
0                           0.0                           0.0   
1                           0.0                           0.0   
2                           0.0                           0.0   
3                           0.0                           0.0   
4                           0.0                           0.0   

   cat__Make_Volkswagen Fox  cat__Make_Volkswagen Passat  cat__Make_Volvo 240  \
0                       0.0                          0.0                  0.0   
1                       0.0                          0.0                  0.0   
2                       0.0                          0.0                  0.0   
3                       0.0                          0.0                  0.0   
4                       0.0                          0.0                  0.0   

   cat__Make_Volvo 850  
0                  0.0  
1                  0.0  
2                  0.0  
3                  0.0  
4                  0.0  

[5 rows x 256 columns]

# TRAIN AND TEST SPLIT

In [22]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain , ytest = train_test_split(X_pre,Y)

In [23]:
xtrain.head()

num__Min.Price  num__Price  num__Max.Price  num__MPG.city  \
84       -0.336343   -0.115503        0.063903       0.471312   
11       -0.991600   -0.635937       -0.328040       0.471312   
59       -0.439804   -0.563077       -0.628833       0.113500   
40       -0.014462    0.030219        0.073018       0.292406   
80       -0.761685   -0.896155       -0.966086       0.471312   

    num__MPG.highway  num__EngineSize  num__Horsepower  num__RPM  \
84          0.549498        -0.453339        -0.169468  0.201098   
11          1.303790        -0.453339        -0.649388 -0.135877   
59         -0.581941        -1.034864        -0.841356  0.790806   
40          0.360925        -0.356418         0.310451  0.875050   
80          0.172352        -0.841022        -1.033324 -0.135877   

    num__Rev.per.mile  num__Fuel.tank.capacity  ...  cat__Make_Toyota Camry  \
84           0.147410                -0.234393  ...                     0.0   
11           0.096786                -0.449005  ...                     0.0   
59           0.289160                -1.706021  ...                     0.0   
40           1.058655                -0.234393  ...                     0.0   
80           2.111649                -0.234393  ...                     0.0   

    cat__Make_Toyota Celica  cat__Make_Toyota Previa  cat__Make_Toyota Tercel  \
84                      1.0                      0.0                      0.0   
11                      0.0                      0.0                      0.0   
59                      0.0                      0.0                      0.0   
40                      0.0                      0.0                      0.0   
80                      0.0                      0.0                      0.0   

    cat__Make_Volkswagen Corrado  cat__Make_Volkswagen Eurovan  \
84                           0.0                           0.0   
11                           0.0                           0.0   
59                           0.0                           0.0   
40                           0.0                           0.0   
80                           0.0                           0.0   

    cat__Make_Volkswagen Fox  cat__Make_Volkswagen Passat  \
84                       0.0                          0.0   
11                       0.0                          0.0   
59                       0.0                          0.0   
40                       0.0                          0.0   
80                       0.0                          0.0   

    cat__Make_Volvo 240  cat__Make_Volvo 850  
84                  0.0                  0.0  
11                  0.0                  0.0  
59                  0.0                  0.0  
40                  0.0                  0.0  
80                  0.0                  0.0  

[5 rows x 256 columns]

# CREATING A LINEAR MODEL 

In [24]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(xtrain,ytrain)

LinearRegression()

# CHECK R2 SCORE IN TEST TRAIN

In [25]:
model.score(xtrain,ytrain)

1.0

In [26]:
model.score(xtest,ytest)

0.9572781754437508

# PREDICTION AND EVALUTION BY MY LIB FN

In [27]:
from mylib import evaluate_model
evaluate_model(xtrain, ytrain , xtest , ytest, model)

Traing results :
MSE : 0.00
RMSE: 0.00
MAE:  0.00
R2:   1.0000
Testing results :
MSE : 17081.41
RMSE: 130.70
MAE:  101.57
R2:   0.9573



# CROSS VALIDATION *******************************

In [28]:
from sklearn.model_selection import cross_val_score
cross_val_score(model,xtrain,ytrain,cv=5,scoring='r2')

array([0.93696542, 0.8677145 , 0.91243341, 0.88697204, 0.89874624])

#        R2 SCORE

In [29]:
r2_scores=cross_val_score(model,xtrain,ytrain,cv=5,scoring='r2')
r2_scores

array([0.93696542, 0.8677145 , 0.91243341, 0.88697204, 0.89874624])

In [30]:
r2_cv = r2_scores.mean()
r2_cv

0.9005663214527939

# MSE CROSS VALIDATION

In [31]:
mse_scores = cross_val_score(model,xtrain,ytrain,cv=5,scoring='neg_mean_squared_error')
mse_scores


array([-23144.82683648, -25538.86358153, -24273.33567666, -25827.53756026,
       -29014.20513094])

In [32]:
mse_cv = - mse_scores.mean()
mse_cv

25559.75375717406

# RMSE CV 

In [33]:
rmse_scores = cross_val_score(model,xtrain,ytrain,cv=5,scoring='neg_root_mean_squared_error')
rmse_scores

array([-152.13423953, -159.80883449, -155.79902335, -160.70948186,
       -170.33556625])

In [34]:
rmse_cv = - mse_scores.mean()
rmse_cv

25559.75375717406

# MAE C V 

In [35]:
mae_scores = cross_val_score(model,xtrain,ytrain,cv=5,scoring='neg_mean_absolute_error')
mae_scores

array([-120.97576609, -110.04846478, -115.83105174, -107.4356083 ,
       -148.47523953])

In [37]:
 mae_cv = - mae_scores.mean()
mae_cv

120.55322608604392

# HYPERPARAMETER TURNING 

In [38]:
import numpy as np

In [39]:
params = {'alpha':np.arange(0.1,100,0.1)}
params

{'alpha': array([ 0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,  1.1,
         1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,  2.2,
         2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,  3.3,
         3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,  4.4,
         4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,  5.5,
         5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,  6.6,
         6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,  7.7,
         7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,  8.8,
         8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,  9.9,
        10. , 10.1, 10.2, 10.3, 10.4, 10.5, 10.6, 10.7, 10.8, 10.9, 11. ,
        11.1, 11.2, 11.3, 11.4, 11.5, 11.6, 11.7, 11.8, 11.9, 12. , 12.1,
        12.2, 12.3, 12.4, 12.5, 12.6, 12.7, 12.8, 12.9, 13. , 13.1, 13.2,
        13.3, 13.4, 13.5, 13.6, 13.7, 13.8, 13.9, 14. , 14.1, 14.2, 14.3,
        14.4, 14.5, 14.6, 14.

In [40]:
from sklearn.linear_model import Ridge
from sklearn.model_selection import GridSearchCV

In [ ]:
rr =Ridge()

In [ ]:
gscv = GridSearchCV(rr,param_grid=params,cv=5,scoring='neg_mean_squared_error')
gscv.fit(xtrain,ytrain)

great search cross validation gscv

In [44]:
gscv.best_params_

{'alpha': 6.0}

In [46]:
gscv.best_score_

-25567.44641063673

In [47]:
best_ridge = gscv.best_estimator_

In [48]:
best_ridge

Ridge(alpha=6.0)

In [49]:
best_ridge.score(xtrain , ytrain)

0.9788480908815423

In [50]:
best_ridge.score(xtest, ytest)

0.9654350766418006

In [51]:
evaluate_model(xtrain, ytrain, xtest , ytest, best_ridge)

Traing results :
MSE : 6177.05
RMSE: 78.59
MAE:  59.40
R2:   0.9788
Testing results :
MSE : 13820.05
RMSE: 117.56
MAE:  92.70
R2:   0.9654


In [52]:
r2_score = cross_val_score(best_ridge, xtrain, ytrain, cv = 5, scoring='r2')
r2_score

array([0.94527099, 0.85123355, 0.91001545, 0.88284986, 0.90469953])

In [53]:
r2_score.mean()

0.8988138759809269

# LASSO HYPERPARAMETER TRAINING

In [55]:
from sklearn.linear_model import Lasso
ls = Lasso()

In [57]:
gscv2 = GridSearchCV(ls, param_grid=params, cv = 5 , scoring='neg_mean_squared_error')
gscv2.fit(xtrain,ytrain)

GridSearchCV(cv=5, estimator=Lasso(),
             param_grid={'alpha': array([ 0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,  1.1,
        1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,  2.2,
        2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,  3.3,
        3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,  4.4,
        4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,  5.5,
        5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,  6.6,
        6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7....
       93.6, 93.7, 93.8, 93.9, 94. , 94.1, 94.2, 94.3, 94.4, 94.5, 94.6,
       94.7, 94.8, 94.9, 95. , 95.1, 95.2, 95.3, 95.4, 95.5, 95.6, 95.7,
       95.8, 95.9, 96. , 96.1, 96.2, 96.3, 96.4, 96.5, 96.6, 96.7, 96.8,
       96.9, 97. , 97.1, 97.2, 97.3, 97.4, 97.5, 97.6, 97.7, 97.8, 97.9,
       98. , 98.1, 98.2, 98.3, 98.4, 98.5, 98.6, 98.7, 98.8, 98.9, 99. ,
       99.1, 99.2, 99.3, 99.4, 99.5, 99.6, 99.7, 99.8, 99.9])},
             scoring='neg_mean_squared_error')

In [58]:
gscv2.best_params_

{'alpha': 4.5}

In [60]:
gscv2.best_score_

-24269.046893302875

In [62]:
best_lasso = gscv2.best_estimator_
best_lasso

Lasso(alpha=4.5)

In [63]:
best_lasso.score(xtrain , ytrain)

0.9614696704215095

In [64]:
best_lasso.score(xtest, ytest)

0.9586406343672459

In [65]:
evaluate_model(xtrain, ytrain, xtest , ytest, best_lasso)

Traing results :
MSE : 11252.11
RMSE: 106.08
MAE:  80.82
R2:   0.9615
Testing results :
MSE : 16536.66
RMSE: 128.59
MAE:  98.08
R2:   0.9586


In [66]:
r2_score = cross_val_score(best_lasso, xtrain, ytrain, cv = 5, scoring='r2')
r2_score

array([0.95206766, 0.84476657, 0.91555198, 0.88828049, 0.91331681])

In [67]:
r2_score.mean()

0.902796702040377

# SELECT BEST MODEL

In [73]:
ypred_tr = best_ridge.predict(xtrain)
ypred_tr

array([[2861.6020182 ],
       [2612.46346881],
       [2448.25802674],
       [2873.76340509],
       [2576.85697755],
       [2285.61170927],
       [3455.77644935],
       [2924.11539231],
       [2179.78397329],
       [3643.99770912],
       [3912.06709284],
       [2721.48334038],
       [3997.12797782],
       [2334.20322333],
       [2977.25438651],
       [3510.41881623],
       [2638.20789868],
       [3760.8370332 ],
       [3103.83898551],
       [3284.0240199 ],
       [4117.09605138],
       [3690.62688801],
       [3007.62941313],
       [3006.49264994],
       [2538.77222043],
       [3503.88103047],
       [2947.06110145],
       [3234.6497255 ],
       [2959.40100556],
       [2958.96061416],
       [4112.86484298],
       [2615.02840247],
       [2887.84803826],
       [3579.16803093],
       [2275.72309595],
       [3886.12807295],
       [3731.60791626],
       [3718.46540006],
       [2784.64240089],
       [3226.2599963 ],
       [3007.4426761 ],
       [2968.039

# PREDCTION OD NEW SAMPLE VALUES


In [75]:
xnew =pd.read_csv('C:Downloads/sample.csv')
xnew.head()

Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Audi      100  Midsize       30.8   37.7       44.6        19   
1      Pontiac  Sunbird  Compact        9.4   11.1       12.8        23   
2    Chevrolet   Lumina  Midsize       13.4   15.9       18.4        21   
3        Mazda     RX-7   Sporty       32.5   32.5       32.5        17   
4   Volkswagen      Fox    Small        8.7    9.1        9.5        25   

   MPG.highway      AirBags DriveTrain  ... Fuel.tank.capacity  Passengers  \
0           26          NaN      Front  ...               21.1           6   
1           31          NaN      Front  ...               15.2           5   
2           29          NaN      Front  ...               16.5           6   
3           25  Driver only       Rear  ...               20.0           2   
4           33          NaN      Front  ...               12.4           4   

   Length  Wheelbase  Width Turn.circle  Rear.seat.room  Luggage.room  \
0     193        106     65          37            31.0          17.0   
1     181        101     66          39            25.0          13.0   
2     198        108     71          40            28.5          16.0   
3     169         96     69          37             NaN           NaN   
4     163         93     63          34            26.0          10.0   

    Origin              Make  
0  non-USA          Audi 100  
1      USA   Pontiac Sunbird  
2      USA  Chevrolet Lumina  
3  non-USA        Mazda RX-7  
4  non-USA    Volkswagen Fox  

[5 rows x 26 columns]

# APPLY PRETRANSFORM OF SAMPLE DATA

In [78]:
xnew_pre = pre.transform(xnew).toarray()
xnew

Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Audi      100  Midsize       30.8   37.7       44.6        19   
1      Pontiac  Sunbird  Compact        9.4   11.1       12.8        23   
2    Chevrolet   Lumina  Midsize       13.4   15.9       18.4        21   
3        Mazda     RX-7   Sporty       32.5   32.5       32.5        17   
4   Volkswagen      Fox    Small        8.7    9.1        9.5        25   

   MPG.highway      AirBags DriveTrain  ... Fuel.tank.capacity  Passengers  \
0           26          NaN      Front  ...               21.1           6   
1           31          NaN      Front  ...               15.2           5   
2           29          NaN      Front  ...               16.5           6   
3           25  Driver only       Rear  ...               20.0           2   
4           33          NaN      Front  ...               12.4           4   

   Length  Wheelbase  Width Turn.circle  Rear.seat.room  Luggage.room  \
0     193        106     65          37            31.0          17.0   
1     181        101     66          39            25.0          13.0   
2     198        108     71          40            28.5          16.0   
3     169         96     69          37             NaN           NaN   
4     163         93     63          34            26.0          10.0   

    Origin              Make  
0  non-USA          Audi 100  
1      USA   Pontiac Sunbird  
2      USA  Chevrolet Lumina  
3  non-USA        Mazda RX-7  
4  non-USA    Volkswagen Fox  

[5 rows x 26 columns]

In [80]:
xnew_pre = pd.DataFrame(xnew_pre,columns=cols)
xnew_pre

num__Min.Price  num__Price  num__Max.Price  num__MPG.city  \
0        1.571949    1.893374        2.069191      -0.602126   
1       -0.888138   -0.875337       -0.829362       0.113500   
2       -0.428309   -0.375720       -0.318925      -0.244313   
3        1.767376    1.352122        0.966282      -0.959938   
4       -0.968608   -1.083511       -1.130155       0.471312   

   num__MPG.highway  num__EngineSize  num__Horsepower  num__RPM  \
0         -0.581941         0.128186         0.540813  0.369586   
1          0.360925        -0.647181        -0.649388 -0.135877   
2         -0.016221        -0.453339        -0.649388 -0.135877   
3         -0.770514        -1.325626         2.134145  2.054464   
4          0.738071        -0.841022        -1.206095  0.369586   

   num__Rev.per.mile  num__Fuel.tank.capacity  ...  cat__Make_Toyota Camry  \
0           0.410659                 1.359872  ...                     0.0   
1           0.673908                -0.449005  ...                     0.0   
2           0.532158                -0.050439  ...                     0.0   
3          -0.014589                 1.022624  ...                     0.0   
4           0.441034                -1.307455  ...                     0.0   

   cat__Make_Toyota Celica  cat__Make_Toyota Previa  cat__Make_Toyota Tercel  \
0                      0.0                      0.0                      0.0   
1                      0.0                      0.0                      0.0   
2                      0.0                      0.0                      0.0   
3                      0.0                      0.0                      0.0   
4                      0.0                      0.0                      0.0   

   cat__Make_Volkswagen Corrado  cat__Make_Volkswagen Eurovan  \
0                           0.0                           0.0   
1                           0.0                           0.0   
2                           0.0                           0.0   
3                           0.0                           0.0   
4                           0.0                           0.0   

   cat__Make_Volkswagen Fox  cat__Make_Volkswagen Passat  cat__Make_Volvo 240  \
0                       0.0                          0.0                  0.0   
1                       0.0                          0.0                  0.0   
2                       0.0                          0.0                  0.0   
3                       0.0                          0.0                  0.0   
4                       1.0                          0.0                  0.0   

   cat__Make_Volvo 850  
0                  0.0  
1                  0.0  
2                  0.0  
3                  0.0  
4                  0.0  

[5 rows x 256 columns]

# PREDICT THE DATA

In [81]:
preds = best_ridge.predict(xnew_pre)
preds

array([[3357.24315739],
       [2735.51972117],
       [3152.5634308 ],
       [3134.69631943],
       [2257.88927292]])

# SAVING THE PREDCTION AND FILE 


In [83]:
xnew['Weight']= preds
xnew

Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Audi      100  Midsize       30.8   37.7       44.6        19   
1      Pontiac  Sunbird  Compact        9.4   11.1       12.8        23   
2    Chevrolet   Lumina  Midsize       13.4   15.9       18.4        21   
3        Mazda     RX-7   Sporty       32.5   32.5       32.5        17   
4   Volkswagen      Fox    Small        8.7    9.1        9.5        25   

   MPG.highway      AirBags DriveTrain  ... Passengers  Length  Wheelbase  \
0           26          NaN      Front  ...          6     193        106   
1           31          NaN      Front  ...          5     181        101   
2           29          NaN      Front  ...          6     198        108   
3           25  Driver only       Rear  ...          2     169         96   
4           33          NaN      Front  ...          4     163         93   

   Width  Turn.circle Rear.seat.room  Luggage.room   Origin              Make  \
0     65           37           31.0          17.0  non-USA          Audi 100   
1     66           39           25.0          13.0      USA   Pontiac Sunbird   
2     71           40           28.5          16.0      USA  Chevrolet Lumina   
3     69           37            NaN           NaN  non-USA        Mazda RX-7   
4     63           34           26.0          10.0  non-USA    Volkswagen Fox   

        Weight  
0  3357.243157  
1  2735.519721  
2  3152.563431  
3  3134.696319  
4  2257.889273  

[5 rows x 27 columns]

In [84]:
xnew.to_csv('sam',index=False )